### ISSUE TITLE
invalid syntax, line 52

### ISSUE THREAD

**Issue by jamesbond007325** [xMNG/Microsoft-Rewards-Bot#45]
Hello so I was trying to set this up on my raspberry pi, I managed to successfully install selenium/requests. But whenever I try running it, I seem to get this invalid syntax error. Any ideas how to fix it? 
(Btw the invalid syntax carrot is pointing to the final apostrophe at the end of the line)

pi@raspberrypi:~ $ python /home/pi/Desktop/microsoft_rewards_bot/Microsoft-Rewards-Bot-master/ms_rewards.py --headless --mobile --pc --quiz
  File "/home/pi/Desktop/microsoft_rewards_bot/Microsoft-Rewards-Bot-master/ms_rewards.py", line 52
    message = f'invalid choice: {log_level_string} (choose from {_LOG_LEVEL_STRINGS})'
                                                                                     ^
SyntaxError: invalid syntax

**Comment by ShoGinn** [comment]
Run it with python3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jamesbond007325** [comment]
I’m not too proficient in python but I’m still getting the error. Is this the correct way of running it in python 3?

pi@raspberrypi:~ $ python3 /home/pi/Desktop/microsoft_rewards_bot/Microsoft-Rewards-Bot-master/ms_rewards.py --headless --mobile --pc --quiz
  File "/home/pi/Desktop/microsoft_rewards_bot/Microsoft-Rewards-Bot-master/ms_rewards.py", line 52
    message = f'invalid choice: {log_level_string} (choose from {_LOG_LEVEL_STRINGS})'
                                                                                     ^
SyntaxError: invalid syntax

**Comment by ShoGinn** [comment]
I could not replicate the error. 

What are the responses to these commands:

```
python --version
```

and

```
python3 --version
```

**Comment by h4x0rm1k3** [comment]
I had the same issue trying to get it to run on a Droplet as I managed to get so far with setting it up now but after updating python i'm now getting a completely different error . I did check the Python version which was 3.5.1 I think so I updated it to 3.6 and version reports 3.6.7 now and now I get a completely different  error show in this pic - [https://imgur.com/a3E40aW](url) . I do have all requirements installed but the only thing I can't install is chrome itself as I have no access to the browser as such (not sure if I can do this from shell).

**Comment by jamesbond007325** [comment]
@shoginn I feel really embarrassed but I think I found the issue, python is at 2.7 while python3 is only at 3.5. I went and updated myself last night to python 3.6 and now my only issue is similar to h4x0rm1k3. Because I’m running it through a raspberry pi, I’m getting the missing module: chrome driver error. Do you have any idea how I can get chrome driver? Should I close this issue and open a new one , or could we continue to use this one?

**Comment by h4x0rm1k3** [comment]
@jamesbond007325 Are you able to install chrome browser on your R-pi? That could be the issue as I run the script no problem on a Windows 10 setup, I just can't get it to run automatically no matter what I try and the batch file doesn't seem to work even though the commands in it will work in a CMD window so i'm trying to set it up on a Digital ocean droplet as it's mentioned it works on them so I can use CRON to automate it. I'm thinking it might be because chrome browser isn't installed because that's the only difference to my windows & droplet versions from what I can tell and as the droplet is shell access only with no GUI i'm stuck at how to try and install chrome browser on it, if that's even the problem that is!

**Comment by jamesbond007325** [comment]
@h4x0rm1k3 that’s the problem I can’t seem to download chrome browser onto raspberry pi, but I think I found a way to install chromedriver onto it. I don’t know what droplet is but if it’s based on Debian, maybe this’ll help? 

https://www.reddit.com/r/selenium/comments/7341wt/success_how_to_run_selenium_chrome_webdriver_on/

Also how are you trying to automate the bat file on windows 10? In the past I’ve always used task scheduler to run bat files on a schedule and it’s worked before.

**Comment by h4x0rm1k3** [comment]
I tried task scheduler as that's my go to normally but it looks like because it's a python script with arguments it's running it doesn't want to know, I even tried with Admin rights etc but no go so i'm stumped with that 1. A droplet is a headless/GUI-less Ubuntu server but can also run a number of others including Debian I think so I might look in to seeing if I can get it to run on that if all else fails, i'll definitely check out what you linked though as that might be the answer or direction I need to look for my same issue i'm having so thanks for that.

**Comment by jamesbond007325** [comment]
I have figured it out, the reddit link above me details exactly how to get chrome driver working on raspberry pi and it does work! It’s doing the searches right now as I speak. Thank you all for all your help!

**Comment by h4x0rm1k3** [comment]
@jamesbond007325 Can you explain how you got it installed please because I can't for the life of me work it out and I tried on both a Ubuntu & Debian server but still get the error in the picture, I even went as so far as to find out how to install chrome-browser manually and checked it was running the correct version and the files were in the right place (I placed the chromedriver & it's folder in a few places just in case!) but still nothing and everything's updated to it's latest with all dependencies installed, I just can't get past this final hurdle so a little run down of which steps you took would be appreciated if you don't mind? Thanks and congrats on working it out at least your end anyway!

**Comment by jamesbond007325** [comment]
@h4x0rm1k3 so I did this with Debian so I’ll explain it through that. To begin with you need to download chromium onto the device. I already had v65 already installed on my machine, notice how it is version v65. 

Next I will be following the reddit instructions. I begin by ensuring selenium is installed by typing “pip install selenium” without quotes. Next I follow the link in the reddit thread and download the chromedriver that matches my version of chromium. For my version of chromium, this link below leads to the version of chrome driver I needed. Notice how it is version 65.0, that’ll ensure there are no errors later. (I have a ui version, so installation was done through that, I believe for terminal only server you need to use “dpckg deb” but I’m not too sure how to use it)

https://launchpad.net/ubuntu/trusty/armhf/chromium-chromedriver/65.0.3325.181-0ubuntu0.14.04.1

Next I head over to line 232 in ms_rewards.py, and modify replace the word “path” with “/usr/lib/chromium-browser/chromedriver”

Now when you try running it, you shouldn’t get the chromedriver error anymore. Hopefully that helps, let me know if it still gives you a hard time.
